export const codesOOM = {
    0  : 'Céu Limpo',
    1  : 'Principalmente claro',
    2  : 'Parcialmente nublado',
    3  : 'Encoberto',
    45 : 'Nevoeiro ',
    48 : 'Neblina depositada',
    51 : 'Chuvisco: Intensidade leve',
    53 : 'Chuvisco: Intensidade moderada',
    55 : 'Chuvisco: Intensidade densa',
    56 : 'Chuvisco Congelante: Intensidade leve',
    57 : 'Chuvisco Congelante: Intensidade densa',
    61 : 'Chuva: Intensidade leve',
    63 : 'Chuva: Intensidade moderada',
    65 : 'Chuva: Intensidade forte',
    66 : 'Chuva Congelante: Intensidade leve',
    67 : 'Chuva Congelante: Intensidade pesada',
    71 : 'Queda de neve: Intensidade leve',
    73 : 'Queda de neve: Intensidade moderada ',
    75 : 'Queda de neve: Intensidade forte',
    77 : 'Grãos de neve',
    80 : 'Pancadas de chuva: leves',
    81 : 'Pancadas de chuva: moderadas ',
    82 : 'Pancadas de chuva: violentas',
    85 : 'Pancadas de neve leves',
    86 : 'Pancadas de neve fortes',
    95 : 'Trovoada: leve ou moderada',
    96 : 'Trovoada com granizo leve',
    99 : 'Trovoada com granizo forte'
  }
  